### ISSUE TITLE
A note on the lib design

### ISSUE THREAD

**Issue by raffs** [mainak90/colorify#1]
First of all, nice lib! 

The idea of: 

```go
// Start the init function
redPrint := red.New()
yellowPrint := yellow.New()

yellowPrint.Println("This is yellow regular!!!")
```

or, representing each color as object is an interesting idea. However, if a cli program wants to have 4 or more colors in its output, like a column-based colorizer which is usually done for coloring logs, this could lead to a lot of go objects that needs to be instantiated.  Thus, maybe representing a simple or static function that you call directly, for example:

```go
colorify.Yellow("This line is yellow: %s", yellowWord)
colorify.Red("This line is red: %s", redWord)
```

without requiring an object to be `new()` might make the library caller a bit simpler to deal with it. Alternatively, you could have one single initialization of the object, the `colorify` object as then use for the other colors:

```go
color = colorify.New(....)

color.Yellowf("This line is yellow: %s", yellowWord)
color.Redf("This line is red: %s", redWord)
```

Isn't too bad to make `new()` all variable, but; it make simpler to use if such or similar facilities are available. And, we the lib could simply allow both way and the caller decide which one to pick for its program :)

**Comment by mainak90** [comment]
agreed, on it!

**Comment by mainak90** [comment]
Implemented!
