### ISSUE TITLE
Allow the user to choose when the color is enable/disable or auto

### ISSUE THREAD

**Issue by raffs** [mainak90/colorify#2]
The [func (c *Colorify) New() *Colorify](https://github.com/mainak90/colorify/blob/main/colorify.go#L55-L69), function uses the `isatty()` to decide when to enable/disable the color based on whether the `stdout` or `/fd/1` points to terminal-like file description. This is very nice way to make the coloring disable automatically when no-terminal is presented. The code will, also; disable coloring when a stdout redirection, such as `|`; is made on the program. For instance, something like:

```bash
log-colorizer file.log | grep -i PCI
```

will automatically disable the coloring of my program when use `colorify` library. As developer, I might to carry over the coloring when a non-terminal like file description is presented. For instance, the user might not want to loose the colors if when using a paginator such as `less` or `more`. 

Therefore, I think it will be nice idea to allow the caller of the library to decide whether:

1. Coloring will be enable/disable automatically based on the `isatty()` function (which is the default)
2. Enable coloring
3. Disable coloring

which is usually expose in the form an command-line option (i.e: `--color=auto|true|false`,) for the cli program. Then, allowing the user to disable/enable at will and leaving the default behavior to automatically decide -- which is the current code. 

One implementation will be to teach the `New()` function a new option that will have three-state variable: `auto`, `true` or `false`, given the developer and, potentially; the user to actually decide when color should be present or not.

**Comment by mainak90** [comment]
Makes sense, missed the conditions on terminals like pipes and paginator options. Marking the option togglable.

**Comment by mainak90** [comment]
Added the PR to check the same.
